// SPDX-License-Identifier: GPL-2.0-or-later OR LGPL-3.0-or-later
/*
 * test_filter - unprivileged conformance tests for the filter engine.
 *
 * For every (filter, packet, expected) vector of WinDivert's own test suite
 * (tests/wd_vectors.c, generated by scripts/sync_windivert.sh):
 *  1. the vendored evaluator must return the expected verdict;
 *  2. the kernel pre-filter must be sound: whenever the exact filter
 *     accepts, the lowered BPF rules accept too;
 *  3. when the lowering is flagged exact, both verdicts must be equal.
 * A second table checks that common filters lower exactly, since that is
 * what keeps user-space evaluation off the fast path.
 */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <arpa/inet.h>

#include "ebpfdivert.h"
#include "prefilter.h"
#include "wd.h"

typedef int BOOL;
#define TRUE    1
#define FALSE   0

#include "wd_vectors.c"

static int failures;

#define FAIL(...)                                   \
    do {                                            \
        fprintf(stderr, "  [FAIL] " __VA_ARGS__);   \
        failures++;                                 \
    } while (0)

static uint32_t rd32(const uint8_t *p)
{
    return ((uint32_t)p[0] << 24) | ((uint32_t)p[1] << 16) |
           ((uint32_t)p[2] << 8) | p[3];
}

static uint16_t rd16(const uint8_t *p)
{
    return (uint16_t)((p[0] << 8) | p[1]);
}

/* Mirror of parse_packet() in ebpfdivert.bpf.c for raw IP packets. */
static int kernel_parse(const uint8_t *b, size_t len, struct pf_pkt *p,
    int *fragment)
{
    const uint8_t *t;
    memset(p, 0, sizeof(*p));
    *fragment = 0;
    if (len < 20)
        return 0;
    p->ver = b[0] >> 4;
    if (p->ver == 4) {
        unsigned ihl = b[0] & 0x0F;
        uint16_t frag_off = rd16(b + 6);
        p->ttl = b[8];
        p->proto = b[9];
        p->src[0] = rd32(b + 12);
        p->src[1] = 0xFFFF;
        p->dst[0] = rd32(b + 16);
        p->dst[1] = 0xFFFF;
        if (ihl < 5)
            return 0;
        if (frag_off & 0x3FFF)
            *fragment = 1;
        if (frag_off & 0x1FFF)
            return 1;
        t = b + ihl * 4;
    } else if (p->ver == 6) {
        uint8_t next;
        int i;
        if (len < 40)
            return 0;
        p->ttl = b[7];
        for (i = 0; i < 4; i++) {
            p->src[3 - i] = rd32(b + 8 + 4 * i);
            p->dst[3 - i] = rd32(b + 24 + 4 * i);
        }
        next = b[6];
        t = b + 40;
        for (i = 0; i < 4; i++) {
            unsigned hlen;
            if (next != 0 && next != 43 && next != 44 && next != 60)
                break;
            if (t + 8 > b + len)
                return 0;
            if (next == 44) {
                *fragment = 1;
                hlen = 8;
            } else {
                hlen = ((unsigned)t[1] + 1) * 8;
            }
            next = t[0];
            t += hlen;
        }
        p->proto = next;
        if (*fragment)
            return 1;
    } else {
        return 0;
    }
    if (p->proto == 6 && t + 20 <= b + len) {
        p->sport = rd16(t);
        p->dport = rd16(t + 2);
        p->tcp_flags = t[13];
    } else if (p->proto == 17 && t + 8 <= b + len) {
        p->sport = rd16(t);
        p->dport = rd16(t + 2);
    } else if ((p->proto == 1 || p->proto == 58) && t + 8 <= b + len) {
        p->sport = t[0];
        p->dport = t[1];
    }
    return 1;
}

/* Kernel verdict: the BPF program lets fragments through to user space
 * whenever the table is non-empty (see process_packet()). */
static int kernel_verdict(const struct pf_result *res, const struct pf_pkt *p,
    int fragment)
{
    if (fragment) {
        if (p->ver == 4)
            return res->n4 > 0 && !(res->v4[0].match_mask & MATCH_FALSE);
        return res->n6 > 0 && !(res->v6[0].match_mask & MATCH_FALSE);
    }
    return pf_match(res, p);
}

static void run_vector(const struct test *t, int idx)
{
    struct wd_filter *f = NULL;
    struct ebpfdivert_address addr;
    struct pf_result res;
    struct pf_pkt pkt;
    const char *err_str;
    unsigned err_pos;
    int exact, kernel, fragment, random_dep;
    int ret;

    random_dep = (strstr(t->filter, "random") != NULL);
    ret = wd_filter_compile(t->filter, EBPFDIVERT_LAYER_NETWORK, &f, &err_str,
        &err_pos);
    if (ret != 0) {
        FAIL("#%d compile '%s': %s at %u\n", idx, t->filter, err_str, err_pos);
        return;
    }

    memset(&addr, 0, sizeof(addr));
    addr.layer = EBPFDIVERT_LAYER_NETWORK;
    addr.outbound = 1;
    addr.ipv6 = ((t->packet->packet[0] >> 4) == 6);
    exact = wd_filter_eval(f, t->packet->packet,
        (unsigned)t->packet->packet_len, &addr);
    if (exact < 0) {
        FAIL("#%d eval '%s' on %s returned %d\n", idx, t->filter,
            t->packet->name, exact);
        goto out;
    }
    if (!random_dep && exact != t->match) {
        FAIL("#%d '%s' on %s: got %d, expected %d\n", idx, t->filter,
            t->packet->name, exact, t->match);
    }

    if (pf_lower(f, &res) != 0) {
        FAIL("#%d lower '%s' failed\n", idx, t->filter);
        goto out;
    }
    if (!kernel_parse(t->packet->packet,
            t->packet->packet_len, &pkt, &fragment)) {
        FAIL("#%d kernel parse of %s failed\n", idx, t->packet->name);
        goto out;
    }
    pkt.direction = 2;      /* outbound */
    pkt.loopback = 0;
    kernel = kernel_verdict(&res, &pkt, fragment);
    if (exact && !kernel) {
        FAIL("#%d unsound pre-filter for '%s' on %s (rules v4=%u v6=%u)\n",
            idx, t->filter, t->packet->name, res.n4, res.n6);
    }
    if (res.exact && !fragment && kernel != exact) {
        FAIL("#%d pre-filter flagged exact but disagrees for '%s' on %s "
            "(kernel %d, exact %d)\n", idx, t->filter, t->packet->name,
            kernel, exact);
    }
out:
    wd_filter_free(f);
}

/* Filters that must lower exactly (no user-space evaluation needed). */
static const char *const exact_filters[] = {
    "true",
    "false",
    "tcp",
    "udp",
    "icmp",
    "icmpv6",
    "ip",
    "ipv6",
    "not tcp",
    "inbound",
    "outbound and udp",
    "loopback",
    "tcp.DstPort == 80",
    "tcp.DstPort == 80 or tcp.SrcPort == 80",
    "tcp.DstPort != 22",
    "udp.DstPort >= 1000 and udp.DstPort <= 2000",
    "tcp.Syn and not tcp.Ack",
    "tcp and tcp.Syn == 1 and tcp.Ack == 0",
    "ip.DstAddr == 10.0.0.1",
    "ip.SrcAddr >= 10.0.0.0 and ip.SrcAddr <= 10.255.255.255",
    "ip.DstAddr != 127.0.0.1",
    "ipv6.DstAddr == ::1",
    "ipv6.SrcAddr >= fe80:: and ipv6.SrcAddr <= fe80::ffff:ffff:ffff:ffff",
    "icmp.Type == 8",
    "icmpv6.Type == 128 and icmpv6.Code == 0",
    "ip.TTL == 64",
    "ip.Protocol == 47",
    "outbound and tcp.DstPort == 443 and ip.DstAddr == 192.168.1.1",
    "localPort == 8080 and tcp",
    "tcp and remotePort == 443",
    "(tcp.DstPort == 80 or udp.DstPort == 53) and outbound",
    NULL
};

/* Filters that must NOT be flagged exact (they need user-space eval). */
static const char *const inexact_filters[] = {
    "tcp.PayloadLength > 100",
    "packet[0] == 0x45",
    "ip.Length < 500",
    "random8 < 128",
    "impostor",
    NULL
};

static void check_exactness(const char *filter, int want_exact)
{
    struct wd_filter *f = NULL;
    struct pf_result res;
    const char *err_str;
    unsigned err_pos;
    if (wd_filter_compile(filter, EBPFDIVERT_LAYER_NETWORK, &f, &err_str,
            &err_pos) != 0) {
        FAIL("compile '%s': %s at %u\n", filter, err_str, err_pos);
        return;
    }
    if (pf_lower(f, &res) != 0) {
        FAIL("lower '%s' failed\n", filter);
    } else if (res.exact != want_exact) {
        FAIL("'%s' lowered %s (v4=%u v6=%u)\n", filter,
            res.exact? "exact": "inexact", res.n4, res.n6);
    }
    wd_filter_free(f);
}


/****************************************************************************/
/* Randomized differential test                                             */
/****************************************************************************/

static uint32_t rng_state = 0x12345678;

static uint32_t rnd(void)
{
    rng_state ^= rng_state << 13;
    rng_state ^= rng_state >> 17;
    rng_state ^= rng_state << 5;
    return rng_state;
}

static const uint16_t fz_ports[] = {0, 22, 53, 80, 443, 1000, 8080, 65535};
static const char *const fz_v4[] = {"10.0.0.1", "10.0.0.2", "127.0.0.1",
                                    "192.168.1.1", "10.255.0.7"};
static const char *const fz_v6[] = {"::1", "fe80::1", "2001:db8::5",
                                    "fe80::ffff"};

static void fz_atom(char *buf, size_t n)
{
    uint16_t p = fz_ports[rnd() % 8];
    static const char *const ops[] = {"==", "!=", "<", "<=", ">", ">="};
    const char *op = ops[rnd() % 6];
    switch (rnd() % 28) {
    case 0: snprintf(buf, n, "tcp"); break;
    case 1: snprintf(buf, n, "udp"); break;
    case 2: snprintf(buf, n, "icmp"); break;
    case 3: snprintf(buf, n, "icmpv6"); break;
    case 4: snprintf(buf, n, "ip"); break;
    case 5: snprintf(buf, n, "ipv6"); break;
    case 6: snprintf(buf, n, "inbound"); break;
    case 7: snprintf(buf, n, "outbound"); break;
    case 8: snprintf(buf, n, "loopback"); break;
    case 9: snprintf(buf, n, "tcp.DstPort %s %u", op, p); break;
    case 10: snprintf(buf, n, "tcp.SrcPort %s %u", op, p); break;
    case 11: snprintf(buf, n, "udp.DstPort %s %u", op, p); break;
    case 12: snprintf(buf, n, "udp.SrcPort %s %u", op, p); break;
    case 13: snprintf(buf, n, "ip.DstAddr %s %s", op, fz_v4[rnd() % 5]); break;
    case 14: snprintf(buf, n, "ip.SrcAddr %s %s", op, fz_v4[rnd() % 5]); break;
    case 15: snprintf(buf, n, "ipv6.DstAddr %s %s", op, fz_v6[rnd() % 4]); break;
    case 16: snprintf(buf, n, "localPort %s %u", op, p); break;
    case 17: snprintf(buf, n, "remotePort %s %u", op, p); break;
    case 18: snprintf(buf, n, "tcp.Syn"); break;
    case 19: snprintf(buf, n, "tcp.Ack == %u", rnd() % 2); break;
    case 20: snprintf(buf, n, "icmp.Type %s %u", op, (rnd() % 2)? 8: 0); break;
    case 21: snprintf(buf, n, "ip.TTL %s %u", op, (rnd() % 2)? 64: 1); break;
    case 22: snprintf(buf, n, "ip.Protocol %s %u", op, (rnd() % 2)? 17: 6); break;
    case 23: snprintf(buf, n, "localAddr %s %s", op, fz_v4[rnd() % 5]); break;
    case 24: snprintf(buf, n, "remoteAddr %s %s", op, fz_v6[rnd() % 4]); break;
    case 25: snprintf(buf, n, "tcp.PayloadLength > %u", rnd() % 20); break;
    case 26: snprintf(buf, n, "packet[9] == %u", (rnd() % 2)? 6: 17); break;
    default: snprintf(buf, n, "icmpv6.Code %s %u", op, rnd() % 2); break;
    }
}

static void fz_expr(char *buf, size_t n, int depth)
{
    char a[512], b[512], c[512];
    unsigned k = (depth <= 0)? 0: rnd() % 5;
    switch (k) {
    case 0: fz_atom(buf, n); break;
    case 1:
        fz_expr(a, sizeof(a), depth - 1);
        fz_expr(b, sizeof(b), depth - 1);
        snprintf(buf, n, "(%s and %s)", a, b);
        break;
    case 2:
        fz_expr(a, sizeof(a), depth - 1);
        fz_expr(b, sizeof(b), depth - 1);
        snprintf(buf, n, "(%s or %s)", a, b);
        break;
    case 3:
        fz_expr(a, sizeof(a), depth - 1);
        snprintf(buf, n, "not %s", a);
        break;
    default:
        fz_expr(a, sizeof(a), depth - 1);
        fz_expr(b, sizeof(b), depth - 1);
        fz_expr(c, sizeof(c), depth - 1);
        snprintf(buf, n, "(%s? %s: %s)", a, b, c);
        break;
    }
}

static void put16(uint8_t *p, uint16_t v) { p[0] = (uint8_t)(v >> 8); p[1] = (uint8_t)v; }

/* Build a random IPv4/IPv6 TCP/UDP/ICMP/other packet; returns its length. */
static size_t fz_packet(uint8_t *b)
{
    int v6 = rnd() % 2;
    unsigned kind = rnd() % 4;       /* tcp, udp, icmp, other */
    uint8_t proto = kind == 0? 6: kind == 1? 17: kind == 2? (v6? 58: 1): 47;
    size_t l3 = v6? 40: 20, l4 = kind == 0? 20: 8, payload = rnd() % 24;
    size_t len = l3 + l4 + payload;
    uint8_t *t = b + l3;
    memset(b, 0, len);
    if (!v6) {
        uint32_t a;
        b[0] = 0x45;
        put16(b + 2, (uint16_t)len);
        b[8] = (rnd() % 2)? 64: 1;
        b[9] = proto;
        inet_pton(AF_INET, fz_v4[rnd() % 5], &a);
        memcpy(b + 12, &a, 4);
        inet_pton(AF_INET, fz_v4[rnd() % 5], &a);
        memcpy(b + 16, &a, 4);
    } else {
        b[0] = 0x60;
        put16(b + 4, (uint16_t)(len - 40));
        b[6] = proto;
        b[7] = (rnd() % 2)? 64: 1;
        inet_pton(AF_INET6, fz_v6[rnd() % 4], b + 8);
        inet_pton(AF_INET6, fz_v6[rnd() % 4], b + 24);
    }
    if (kind == 0) {
        put16(t, fz_ports[rnd() % 8]);
        put16(t + 2, fz_ports[rnd() % 8]);
        t[12] = 0x50;
        t[13] = (uint8_t)(rnd() & 0x3F);
    } else if (kind == 1) {
        put16(t, fz_ports[rnd() % 8]);
        put16(t + 2, fz_ports[rnd() % 8]);
        put16(t + 4, (uint16_t)(l4 + payload));
    } else if (kind == 2) {
        t[0] = (rnd() % 2)? 8: 0;
        t[1] = (uint8_t)(rnd() % 2);
    }
    return len;
}

static void fuzz(int iterations)
{
    uint8_t pkt[128];
    char filter[4096];
    int i, j, compiled = 0, exact_count = 0;
    for (i = 0; i < iterations; i++) {
        struct wd_filter *f = NULL;
        struct pf_result res;
        const char *err_str;
        unsigned err_pos;
        fz_expr(filter, sizeof(filter), 1 + (int)(rnd() % 3));
        if (wd_filter_compile(filter, EBPFDIVERT_LAYER_NETWORK, &f, &err_str,
                &err_pos) != 0)
            continue;       /* e.g. too long */
        compiled++;
        if (pf_lower(f, &res) != 0) {
            FAIL("fuzz: lower '%s' failed\n", filter);
            wd_filter_free(f);
            continue;
        }
        exact_count += res.exact;
        for (j = 0; j < 32; j++) {
            struct ebpfdivert_address addr;
            struct pf_pkt kp;
            int frag, exact, kernel;
            size_t len = fz_packet(pkt);
            memset(&addr, 0, sizeof(addr));
            addr.layer = EBPFDIVERT_LAYER_NETWORK;
            addr.outbound = rnd() % 2;
            addr.loopback = rnd() % 2;
            addr.ipv6 = (pkt[0] >> 4) == 6;
            exact = wd_filter_eval(f, pkt, (unsigned)len, &addr);
            if (exact < 0 || !kernel_parse(pkt, len, &kp, &frag))
                continue;
            kp.direction = addr.outbound? 2: 1;
            kp.loopback = addr.loopback;
            kernel = kernel_verdict(&res, &kp, frag);
            if (exact && !kernel) {
                FAIL("fuzz: unsound pre-filter for '%s'\n", filter);
                break;
            }
            if (res.exact && kernel != exact) {
                FAIL("fuzz: exact pre-filter disagrees for '%s' (kernel %d, "
                    "exact %d)\n", filter, kernel, exact);
                break;
            }
        }
        wd_filter_free(f);
        if (failures > 20)
            break;
    }
    printf("Fuzzed %d filters (%d lowered exactly).\n", compiled, exact_count);
}

/****************************************************************************/
/* Checksums                                                                */
/****************************************************************************/

static uint32_t sum16(const uint8_t *p, size_t n, uint32_t s)
{
    size_t i;
    for (i = 0; i + 1 < n; i += 2)
        s += (uint32_t)((p[i] << 8) | p[i + 1]);
    if (n & 1)
        s += (uint32_t)(p[n - 1] << 8);
    return s;
}

static int folds_to_ffff(uint32_t s)
{
    while (s >> 16)
        s = (s & 0xFFFF) + (s >> 16);
    return s == 0xFFFF;
}

/*
 * wd_calc_checksums() must produce checksums an independent implementation
 * accepts (the vendored code once miscompiled under strict aliasing).
 */
static void check_checksums(void)
{
    static const struct packet *const pkts[] = {
        &pkt_echo_request, &pkt_http_request, &pkt_dns_request, &pkt_ipv6_tcp_syn,
        &pkt_ipv6_echo_reply, &pkt_ipv6_exthdrs_udp,
    };
    size_t i;
    printf("Checking checksum computation...\n");
    for (i = 0; i < sizeof(pkts) / sizeof(pkts[0]); i++) {
        uint8_t buf[2048];
        struct wd_packet_info info;
        size_t len = pkts[i]->packet_len;
        uint32_t s = 0, l4_len;
        const uint8_t *t;
        memcpy(buf, pkts[i]->packet, len);
        if (wd_calc_checksums(buf, (unsigned)len, NULL, 0) != 0 ||
            wd_parse_packet(buf, (unsigned)len, &info) != 0 || info.transport_off < 0) {
            FAIL("checksum setup for %s\n", pkts[i]->name);
            continue;
        }
        t = buf + info.transport_off;
        l4_len = (uint32_t)(len - (size_t)info.transport_off);
        if (!info.ipv6 && !folds_to_ffff(sum16(buf, (size_t)(buf[0] & 0x0F) * 4, 0)))
            FAIL("bad IPv4 header checksum for %s\n", pkts[i]->name);
        if (info.protocol == 6 || info.protocol == 17 || info.protocol == 58) {
            uint8_t tail[4] = {0, 0, 0, info.protocol};
            if (info.ipv6) {
                uint8_t l[4] = {(uint8_t)(l4_len >> 24), (uint8_t)(l4_len >> 16),
                                (uint8_t)(l4_len >> 8), (uint8_t)l4_len};
                s = sum16(buf + 8, 32, 0);
                s = sum16(l, 4, s);
            } else {
                uint8_t l[4] = {0, info.protocol, (uint8_t)(l4_len >> 8), (uint8_t)l4_len};
                s = sum16(buf + 12, 8, 0);
                s = sum16(l, 4, s);
                memset(tail, 0, sizeof(tail));
            }
            s = sum16(tail, 4, s);
        }
        if (!folds_to_ffff(sum16(t, l4_len, s)))
            FAIL("bad transport checksum for %s\n", pkts[i]->name);
    }
}

/****************************************************************************/
/* SOCKET-layer lowering (kernel blocking decisions)                        */
/****************************************************************************/

/* Mirror of rule_match() in ebpfdivert_events.bpf.c. */
static int ev_addr_match(const uint8_t *a, const uint8_t *ip, const uint8_t *m)
{
    int i;
    for (i = 0; i < 16; i++)
        if ((a[i] & m[i]) != (ip[i] & m[i]))
            return 0;
    return 1;
}

static int ev_rules_match(const struct event_rule *rules, unsigned n, const struct divert_event *e)
{
    unsigned i;
    for (i = 0; i < n; i++) {
        const struct event_rule *r = &rules[i];
        uint32_t mm = r->match_mask, inv = r->invert_mask;
        if ((mm & EVM_EVENT) && !(r->event_mask & (1 << e->event))) continue;
        if ((mm & EVM_FAMILY) && e->family != r->family) continue;
        if ((mm & EVM_PROTO) && ((e->protocol == r->proto) == !!(inv & EVM_PROTO))) continue;
        if ((mm & EVM_LPORT) && ((e->local_port >= r->lport_lo && e->local_port <= r->lport_hi) ==
                                 !!(inv & EVM_LPORT))) continue;
        if ((mm & EVM_RPORT) && ((e->remote_port >= r->rport_lo && e->remote_port <= r->rport_hi) ==
                                 !!(inv & EVM_RPORT))) continue;
        if ((mm & EVM_PID) && ((e->pid >= r->pid_lo && e->pid <= r->pid_hi) == !!(inv & EVM_PID))) continue;
        if ((mm & EVM_LADDR) && (ev_addr_match(e->local_addr, r->laddr, r->lmask) == !!(inv & EVM_LADDR))) continue;
        if ((mm & EVM_RADDR) && (ev_addr_match(e->remote_addr, r->raddr, r->rmask) == !!(inv & EVM_RADDR))) continue;
        return 1;
    }
    return 0;
}

/* Build the WINDIVERT_ADDRESS the filter evaluator sees for an event. */
static void ev_address(const struct divert_event *e, struct ebpfdivert_address *a)
{
    int i;
    memset(a, 0, sizeof(*a));
    a->layer = EBPFDIVERT_LAYER_SOCKET;
    a->event = e->event;
    a->ipv6 = (e->family == 6);
    a->socket.endpoint_id = e->endpoint_id;
    a->socket.process_id = e->pid;
    a->socket.protocol = e->protocol;
    a->socket.local_port = e->local_port;
    a->socket.remote_port = e->remote_port;
    for (i = 0; i < 4; i++) {
        a->socket.local_addr[3 - i] = rd32(e->local_addr + 4 * i);
        a->socket.remote_addr[3 - i] = rd32(e->remote_addr + 4 * i);
    }
}

static const char *const ev_v4[] = {"10.0.0.1", "127.0.0.1", "192.168.1.1"};
static const char *const ev_v6[] = {"::1", "fe80::1", "2001:db8::5"};

static void ev_random(struct divert_event *e)
{
    static const uint16_t ports[] = {0, 53, 80, 443, 1024, 8080};
    memset(e, 0, sizeof(*e));
    e->event = (uint8_t)(3 + rnd() % 5);       /* BIND..CLOSE */
    e->protocol = (rnd() % 2)? 6: 17;
    e->family = (rnd() % 2)? 4: 6;
    e->pid = (rnd() % 2)? 1234: 42;
    e->local_port = ports[rnd() % 6];
    e->remote_port = ports[rnd() % 6];
    if (e->family == 4) {
        e->local_addr[10] = e->local_addr[11] = e->remote_addr[10] = e->remote_addr[11] = 0xFF;
        inet_pton(AF_INET, ev_v4[rnd() % 3], e->local_addr + 12);
        inet_pton(AF_INET, ev_v4[rnd() % 3], e->remote_addr + 12);
    } else {
        inet_pton(AF_INET6, ev_v6[rnd() % 3], e->local_addr);
        inet_pton(AF_INET6, ev_v6[rnd() % 3], e->remote_addr);
    }
}

static void ev_atom(char *buf, size_t n)
{
    static const char *const events[] = {"BIND", "CONNECT", "LISTEN", "ACCEPT", "CLOSE"};
    static const char *const ops[] = {"==", "!=", "<", "<=", ">", ">="};
    static const uint16_t ports[] = {0, 53, 80, 443, 1024, 8080};
    const char *op = ops[rnd() % 6];
    switch (rnd() % 11) {
    case 0: snprintf(buf, n, "event == %s", events[rnd() % 5]); break;
    case 1: snprintf(buf, n, "event != %s", events[rnd() % 5]); break;
    case 2: snprintf(buf, n, "localPort %s %u", op, ports[rnd() % 6]); break;
    case 3: snprintf(buf, n, "remotePort %s %u", op, ports[rnd() % 6]); break;
    case 4: snprintf(buf, n, "processId %s %u", op, (rnd() % 2)? 1234: 42); break;
    case 5: snprintf(buf, n, "protocol %s %u", op, (rnd() % 2)? 6: 17); break;
    case 6: snprintf(buf, n, "tcp"); break;
    case 7: snprintf(buf, n, "udp"); break;
    case 8: snprintf(buf, n, (rnd() % 2)? "ip": "ipv6"); break;
    case 9: snprintf(buf, n, "remoteAddr %s %s", op, ev_v4[rnd() % 3]); break;
    default: snprintf(buf, n, "localAddr %s %s", op, ev_v6[rnd() % 3]); break;
    }
}

static void ev_expr(char *buf, size_t n, int depth)
{
    char a[512], b[512];
    unsigned k = (depth <= 0)? 0: rnd() % 4;
    if (k == 0) {
        ev_atom(buf, n);
        return;
    }
    ev_expr(a, sizeof(a), depth - 1);
    if (k == 3) {
        snprintf(buf, n, "not %s", a);
        return;
    }
    ev_expr(b, sizeof(b), depth - 1);
    snprintf(buf, n, "(%s %s %s)", a, k == 1? "and": "or", b);
}

static void fuzz_events(int iterations)
{
    char filter[2048];
    int i, j, exact_count = 0, compiled = 0;
    static const char *const must_be_exact[] = {
        "event == CONNECT and remotePort == 443",
        "event == BIND and localPort < 1024 and tcp",
        "processId == 1234 and event == CONNECT and remoteAddr == 10.0.0.1",
        "event == CONNECT and remoteAddr == ::1",
        NULL
    };
    printf("Checking SOCKET-layer lowering...\n");
    for (i = 0; must_be_exact[i]; i++) {
        struct wd_filter *f = NULL;
        struct event_rule rules[EVENT_RULES_MAX];
        unsigned n;
        int exact;
        const char *err_str;
        unsigned err_pos;
        if (wd_filter_compile(must_be_exact[i], EBPFDIVERT_LAYER_SOCKET, &f, &err_str, &err_pos) != 0) {
            FAIL("compile '%s': %s\n", must_be_exact[i], err_str);
            continue;
        }
        pf_lower_events(f, rules, EVENT_RULES_MAX, &n, &exact);
        if (!exact)
            FAIL("'%s' lowered inexact\n", must_be_exact[i]);
        wd_filter_free(f);
    }
    for (i = 0; i < iterations; i++) {
        struct wd_filter *f = NULL;
        struct event_rule rules[EVENT_RULES_MAX];
        unsigned n;
        int exact;
        const char *err_str;
        unsigned err_pos;
        ev_expr(filter, sizeof(filter), 1 + (int)(rnd() % 3));
        if (wd_filter_compile(filter, EBPFDIVERT_LAYER_SOCKET, &f, &err_str, &err_pos) != 0)
            continue;
        compiled++;
        pf_lower_events(f, rules, EVENT_RULES_MAX, &n, &exact);
        if (exact) {
            exact_count++;
            for (j = 0; j < 32; j++) {
                struct divert_event e;
                struct ebpfdivert_address a;
                int want, got;
                ev_random(&e);
                ev_address(&e, &a);
                want = wd_filter_eval(f, NULL, 0, &a);
                got = ev_rules_match(rules, n, &e);
                if (want < 0 || want != got) {
                    FAIL("socket lowering disagrees for '%s' (event %u): filter %d, rules %d\n",
                         filter, e.event, want, got);
                    break;
                }
            }
        }
        wd_filter_free(f);
        if (failures > 20)
            break;
    }
    printf("Fuzzed %d SOCKET filters (%d lowered exactly).\n", compiled, exact_count);
}

int main(void)
{
    size_t i, n = sizeof(tests) / sizeof(tests[0]);

    printf("Running %zu WinDivert filter vectors...\n", n);
    for (i = 0; i < n; i++)
        run_vector(&tests[i], (int)i);

    printf("Checking pre-filter exactness...\n");
    for (i = 0; exact_filters[i] != NULL; i++)
        check_exactness(exact_filters[i], 1);
    for (i = 0; inexact_filters[i] != NULL; i++)
        check_exactness(inexact_filters[i], 0);

    check_checksums();

    printf("Running randomized differential test...\n");
    fuzz(20000);
    fuzz_events(20000);

    if (failures) {
        printf("%d failure(s)\n", failures);
        return 1;
    }
    printf("All filter tests passed.\n");
    return 0;
}
