#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-2.0-or-later OR LGPL-3.0-or-later
#
# Re-vendor the WinDivert helper sources (filter compiler/evaluator, packet
# parser, checksums, hash) and the filter test vectors from a WinDivert
# checkout.  The copied files must stay unmodified: all porting lives in
# src/wd/compat/windows.h and src/wd/wd_port.c.
#
# Usage: scripts/sync_windivert.sh [path/to/windivert]   (default: ../windivert)
set -euo pipefail

here="$(cd "$(dirname "$0")/.." && pwd)"
wd="${1:-$here/../windivert}"
dst="$here/src/wd"

for f in include/windivert.h include/windivert_device.h \
         dll/windivert_shared.c dll/windivert_hash.c dll/windivert_helper.c; do
    cp "$wd/$f" "$dst/"
done

rev="$(git -C "$wd" rev-parse HEAD 2>/dev/null || echo unknown)"
ver="$(cat "$wd/VERSION" 2>/dev/null || echo unknown)"
printf 'WinDivert %s (%s)\n' "$ver" "$rev" > "$dst/WINDIVERT_VERSION"

# Test vectors: packet bytes + the (filter, packet, expected) table.
out="$here/tests/wd_vectors.c"
{
    echo "/* Generated by scripts/sync_windivert.sh from WinDivert $ver ($rev). */"
    echo "/* Source: windivert/test/test_data.c and windivert/test/test.c. */"
    echo
    sed -n '/^static /,$p' "$wd/test/test_data.c"
    echo
    echo "struct packet"
    echo "{"
    echo "    const unsigned char *packet;"
    echo "    size_t packet_len;"
    echo "    char *name;"
    echo "};"
    echo
    echo "struct test"
    echo "{"
    echo "    const char *filter;"
    echo "    const struct packet *packet;"
    echo "    BOOL match;"
    echo "};"
    echo
    awk '/^static const struct packet /{on=1} /^static const struct test tests\[\] =/{exit} on{print}' \
        "$wd/test/test.c"
    sed -n '/^static const struct test tests\[\] =/,/^};$/p' "$wd/test/test.c"
} > "$out"
echo "Synced from $wd ($ver, $rev)"
